### ISSUE TITLE
Добавить шаблоны для HTTP-запросов

### ISSUE THREAD

**Issue by serggukov** [stasganiev/OnesTemplates#1]
Полезно было бы добавить часто используемые конструкции:

- HTTPСоединение
- HTTPЗапрос
- HTTPОтвет

HTTPЗапрос для разных методов GET/POST/PUT, с параметрами и т.д.

**Comment by serggukov** [comment]
Для HTTPОтвет можно составить соответствие возможных кодов ответов.

**Comment by stasganiev** [comment]
Хорошее предложение, ставлю в план на следующий релиз

**Comment by stasganiev** [comment]
Реализован в версии 8.3.4
