### ISSUE TITLE
Для структуры модуля объекта добавить текст

### ISSUE THREAD

**Issue by Untru** [stasganiev/OnesTemplates#11]
Предлагаю для структуры модуля объекта добавить текст по стандартам 1с

#Иначе
ВызватьИсключение НСтр("ru = 'Недопустимый вызов объекта на клиенте.'");

**Comment by stasganiev** [comment]
Принято, благодарю

**Comment by Untru** [comment]
https://github.com/stasganiev/OnesTemplates/issues/7 Уже исправлено, видимо не последняя версия у меня

**Comment by stasganiev** [comment]
Исправлено ранее #7
